close all
clear;clc

% !!! Download 'bruker_data.mat' from the BassData folder on Box so you
% don't have to run RussRecon

% This script loads in k space data and displays a slice of the image data.
% It then uses a sampling mask to generate undersampled k space data and
% displays three different types of reconstructions: zero-filled recon
% (i.e. directly reconstructing the data), SENSE reconstruction
% (autocalibrated), and ESPIRiT reconstruction (using ESPIRiT calibration)

% BART must be installed for bart commands to work
% %! means these settings must be changed for each user depending on where
% your code/BART path is
% %* means you can toggle these options

main_dir = '/Users/janetchen/Documents/Bass Connections'; %!
bartpath = '/Applications/bart/matlab'; %!*
setenv('TOOLBOX_PATH','/Applications/bart') %!

% The following packages are needed in your main directory:
paths = {main_dir;[main_dir '/STI_Suite_v2/STI_Suite_v2.1/Source Code_v2.1'];...
    [main_dir '/RussRecon'];[main_dir '/ImageProcessing'];...
    [main_dir '/NIfTI_20140122'];[main_dir '/MultipleEchoRecon'];...
    [main_dir '/XCalc']};

% If you need to extract the image data, you need to have the .work folder
% in the main directory. If you're loading it in (and bruker_img.MAT should
% be in the addecode main directory), you don't need this folder
workpath = [main_dir '/B04027.work'];

use_espirit_data = false; %* try out the example image or use our image?
% If you want to use the example image, the BART folder at
% https://github.com/mikgroup/espirit-matlab-examples must be downloaded
% (or just the 'full.cfl' from the 'data' folder). Put the correct path
% name here (don't include the '.cfl' at the end):
fullpath = 'BART/espirit-matlab-examples-master/data/full';

bart_mask = false; %* use variable density Poisson mask generated by BART
% code (true), or code from BJ Anderson (false)? Right now, the
% undersampling factor can be better controlled by the Anderson code

load_data = true; %* 'true' if you have the k space data saved and don't
% want to run get_RussRecon_img again
save_data = false; %* 'true' if you want to save the data
data_path = 'bruker_data.mat'; % image path if it's already been saved

addpath(bartpath)
addpath(main_dir)
if ~use_espirit_data && ~load_data % Need to be in workpath for RussRecon
    cd(workpath)
    % Add paths so that RussRecon can be used
    for ii = 1:length(paths)
        addpath(paths{ii,1})
    end
end

if use_espirit_data
    % Read in k space data from BART's example (fully sampled)
    ksp_data = readcfl(sprintf('%s/%s',main_dir,fullpath));
else
    if load_data
        % Load in previously-extracted k space data
        load(sprintf('%s/%s',main_dir,data_path))
    else
        % Get k space data from .work directory
        ksp_data=get_RussRecon_img('bruker','center','save');
        % If data should be saved, save it
        if save_data
            save(sprintf('%s/%s',main_dir,data_path),'bruker_data')
        end
    end
end

% If you want to write the data to a cfl file for BART
%cflpath = sprintf('%s/img',paths{2,1});
%writecfl(cflpath,img)

% The MRI-specific BART commands assume that the first three dimensions
% represent space/spatial k-space, the next two dimensions represent coils
% and ESPIRiT maps, and the 10th dimension (zero-indexing) represents
% temporal phases.

num_coils = size(ksp_data,4);
if use_espirit_data
    % img is 1x230x180x8
    % Swap x, y, z dimensions so 3rd dimension is 1
    ksp_data_echo1 = permute(ksp_data(1,:,:,1:num_coils),[2,3,1,4]); 
    % Take inverse Fourier transform
    coilimg = bart('fft -i 6', ksp_data);
    % Take the root sum of squares to produce one image from multiple coils
    rss = bart('rss 4',squeeze(coilimg));
    slice = 1; % Original X dimension is 1 in length, so use that 'slice'
    sz_x = size(ksp_data,2); sz_y = size(ksp_data,3);
else
    % Z-axis slice to look at
    slice = 52;
    % 8 echoes, 2 coils
    % Original k space data dimensions: x, y, z, # echoes, # coils
    % ksp_data matrix is 192x192x90x8x2
    sz_x = size(ksp_data,1); sz_y = size(ksp_data,2);
    
    % To match espirit 'full' img dimensions (XxYxcoils, 230x180x8), slice
    % in z-dimension IN IMAGE domain
    
    % Inverse Fourier transform the k space data to get the image data
    % 'squeeze' just removes singleton dimensions (i.e. dimensions of
    % length 1)
    temp = bart('fft -i 7',squeeze(ksp_data(:,:,:,1,:)));
    % Another method to get the ifft: ifftnc(<matrix>);
    
    % Take the z-axis slice
    coilimg = temp(:,:,slice,:);
    % Fourier transform back to k space
    % ksp_data_echo1 here is 192x192x1x2 (XxYxZxcoils). This will be used
    % later to get the undersampled data
    ksp_data_echo1 = bart('fft 7',coilimg);
    
    % Take the root sum of squares to produce one image from multiple coils
    rss = bart('rss 4', squeeze(coilimg));
end

fig = figure;
ax = gca;

imshow(abs(rss),[])
% For some reason, when you've used imshow and you don't put in the current
% axis, the title appears on the previous axis
title(ax,'Original image','FontSize',15)
set(fig,'Position',[50 600 300 250])

%% Generate sampling pattern and undersample K-space

% Coil # for which to plot k space data and undersampling
coil = 1;

if bart_mask
    % bart poisson -Y $dim -Z $dim -y $yaccel -z $zaccel -C $caldim -v -e mask
    % -Y: dim 1. -Z: dim 2. -v: variable density (which the workshop uses)
    % -e: elliptical scanning
    % Default values: Y: 192, Z: 192, y: 1.5, z: 1.5, C: 32
    % Change C to 20?
    % ~25% of elements in und2x2 in espirit.m were nonzero
    % !!! Although this should reflect 9216 points, only 8005 points are
    % generated
    num_points = sz_x*sz_y*0.25;
    
    % Sampling pattern. Binary mask (ones and zeros), where ones are the
    % only points that we sample
    % Original output of BART command is 3 dimensional, with first
    % dimension of length 1, so squeeze to remove this dimension
    sampling_pattern = squeeze(bart(sprintf('poisson -Y %d -Z %d -y 1 -z 1 -C 32 -R %d -v -e',sz_x,sz_y,num_points)));% -v -e');
else
    % Mask from BJ Anderson's code
    
    % Inputs
    acceleration = 4; %* Undersample by a factor of <acceleration>
    pa = 2.3;
    pb = 5.6;
    
    % Sampling pattern. Logical binary mask (ones and zeros), where ones
    % indicate the only points that we sample
    sampling_pattern = sampling_mask(acceleration,sz_x,sz_y,pa,pb);
end

% Show how much of the data is kept
fprintf(sprintf('Mask non-zero percentage: %.2f%%',length(find(sampling_pattern ~= 0))/numel(sampling_pattern)*100))
fprintf('\n')

% Plot the original k space, sampling mask, and undersampled k space for
% previously sliced data
fig2 = figure;
s1 = subplot(1,3,1);
imagesc(abs(squeeze(ksp_data_echo1(:,:,1,coil))))
title(sprintf('Original K-space for coil %d',coil),'FontSize',15)

s2 = subplot(1,3,2);
imagesc(sampling_pattern);
title('Sampling pattern','FontSize',15)

% Zero out unsampled areas through element-by-element multiplication with
% sampling pattern
% 'us' means 'undersampled'
us_ksp_data_echo1 = bart('fmac',squeeze(ksp_data_echo1),sampling_pattern); % img_echo1.*sampling_pattern;

s3 = subplot(1,3,3);
imagesc(abs(us_ksp_data_echo1(:,:,1,coil)))
title(sprintf('Undersampled K-space for coil %d',coil),'FontSize',15)

s = suptitle(sprintf('Slice %d of z-axis',slice));
set(s,'FontSize',16,'FontWeight','bold')
set(fig2,'Position',[300 600 800 300])

if use_espirit_data
    n = num_coils;
else
    n = 2; % 2 x n espirit maps, we have 2 coils
end

%% Zero-filled reconstruction versus ESPIRiT

% Zero-filled reconstruction (i.e. direct rss from undersampled data)
% Do IFFT to get image data
us_coilimg = bart('fft -i 7',us_ksp_data_echo1);
% Combine coil data using root sum of squares
us_rss = bart('rss 8', us_coilimg);

% Add singleton dimension so first 3 dimensions reflect x, y, z
us_ksp_data_echo1_slice = permute(us_ksp_data_echo1,[1,2,4,3]);

% !!! assess quality of reconstruction with difference map

% SENSE reconstruction
% Maps generated using autocalibration
sensemaps = bart('caldir 20', us_ksp_data_echo1_slice);
% 'PICS' - parallel-imaging compressed-sensing reconstruction
% Use sliced, undersampled k space data and generated maps to reconstruct
% image
sensereco = bart('pics -r0.01', us_ksp_data_echo1_slice, sensemaps);

% ESPIRiT reconstruction

% Maps generated using ESPIRiT calibration
% % Dimensions from espirit.m:
% % Input to this was 1x230x180x8 (breaks if input is 3D). Expects 3 k space
% % dimensions, 1 coil dimension
% % calib dims: 1x230x180x8x2 (two sets of maps)
% % emaps dims: 1x230x180x1x2
% % [calib emaps] = bart('ecalib -r 20', <image slice>);
% % r: cal size. k: kernel size. m: # maps.
espiritmaps = bart('ecalib -r 20 -k 5 -m 2', us_ksp_data_echo1_slice); %bart('ecalib -S', us_img_slice_dim4);
% size of input 1 = size of input 2
% l1-wavelet, l2 regularization
% r: regularization parameter
espiritreco = bart('pics -l2 -r0.01', us_ksp_data_echo1_slice, espiritmaps);
% espiritreco_rss dims in espirit.m were 1x320x252
espiritreco_rss = bart('rss 16', espiritreco);


% View ESPIRiT maps
fig3 = figure;
ax = gca;
imshow3(abs(squeeze(espiritmaps)),[],[2,n])
title(ax,'ESPIRiT maps','FontSize',15)
set(fig3,'Position',[50 100 400 400])

% Comparisons of different reconstruction methods
% Zero-filled reconstruction
fig4 = figure;
subplot(2,2,1)
ax = gca;
imshow(abs(us_rss(:,:,1)),[])
title(ax,'Zero-filled reconstruction','FontSize',15);

subplot(2,2,2)
ax = gca;
imshow(abs(squeeze(espiritreco(:,:,:,1,1))), [])
title(ax,'ESPIRiT recon (map 1)','FontSize',15)

% This image should be the most accurate/closest to image from fully
% sampled k space
subplot(2,2,3)
ax = gca;
imshow(squeeze(espiritreco_rss),[]);
title(ax,'ESPIRiT rss','FontSize',15)

subplot(2,2,4)
ax = gca;
imshow(abs(squeeze(sensereco)),[])
title(ax,'SENSE reconstruction','FontSize',15)
set(fig4,'Position',[450 100 400 400])